version: '2'
services:
 ons-postgres:
  build: ./postgres
  ports:
   - "5432:5432"
  volumes:
     - .:/code
 redis:
  image: redis
  ports:
   - "6379:6379"
 rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "4369:4369"
    - "25672:25672"
    - "5671-5672:5671-5672"
    - "15671-15672:15671-15672"
