version: '2'
services:
  party:
    container_name: party
    image: sdcplatform/party
    ports: 
     - "5062:5062"
    environment:
     - PORT=5062
     - collectionexercise-service.host=${COLLEX_HOST}
     - survey-service.host=${SURVEY_HOST}
     - case-service.host=${CASE_HOST}
     - iac-service.host=${IAC_HOST}
     - ras-party-db.schema=partysvc
     - ras-party-db.uri=postgresql://postgres@postgres:5432/postgres
    command:
     - docker exec postgres psql -U postgres -d postgres -f party_test_data.sql
  collection_instrument:
    container_name: collection_instrument
    image: sdcplatform/collection_instrument
    ports:
     - "8081:8080"
    environment:
     - db_name=postgres
     - db_host=postgres
     - db_connection=postgresql://postgres@postgres:5432/postgres
    command:
     docker exec postgres psql -U postgres -d postgres -f collection_instrument_test_data.sql
networks:
  default:
    external:
      name: rmdockerdev_default
